### ISSUE TITLE
Document taking screenshots

### ISSUE THREAD

**Issue by schrepfler** [CodeYellowBV/run-headless-chromium#12]
Can we add some examples how to capture screenshots in the documentation?

**Comment by Rob--W** [comment]
This is not built-in, but you can create an extension that uses the [`chrome.tabs.captureVisibleTab`](https://developer.chrome.com/extensions/tabs#method-captureVisibleTab) API and load this extension via `--load-extension`. Then send the captured screenshot to some custom API endpoint.

**Comment by schrepfler** [comment]
Is this the same headless chromium as this https://docs.google.com/document/d/11zIkKkLBocofGgoTeeyibB2TZ_k7nR78v7kNelCatUE/edit#heading=h.1mcyhpdqtjob as if yes, I would expect it to provide a direct API to be able to do it?

**Comment by Rob--W** [comment]
They are different.

This repository offers `run-headless-chromium`, a tool that uses Xvfb to launch a real Chrome browser.

The document that you're linking to describes how advanced users can use the technology from Chromium in headless mode. There are no official "headless Chromium" binaries (it would be called `headless_shell` by default), you have to compile it yourself. After doing that, you can start `headless_shell` and use the remote debugging protocol to capture screenshots (using the `Page.captureScreenshot` devtools command, as documented at https://chromedevtools.github.io/debugger-protocol-viewer/tot/Page/#method-captureScreenshot).

**Comment by schrepfler** [comment]
Cool, that clarifies it. I think this headless_shell has a lot of potential for a Docker container as well, especially if they make a nice js wrapper on top of the lib.Thanks for the input!
