### ISSUE TITLE
Chrome 56 issue?

### ISSUE THREAD

**Issue by abzainuddin** [CodeYellowBV/run-headless-chromium#13]
I've just upgraded from chromium 50 to 56, and it seems that the `console.log` output is formatted differently:

`[20024:20024:0201/131223.031836:INFO:CONSOLE(40)] "All tests completed!0", source: webpack:///./src/test/boot/console.js? (40)`

It seems that `run-headless-chromium` cannot detect the magic string and doesn't terminate.

**Comment by Rob--W** [comment]
Fixed and published in 0.1.1
