### ISSUE TITLE
headless without xvfb

### ISSUE THREAD

**Issue by graingert** [CodeYellowBV/run-headless-chromium#6]
It would be great to support chromium without a head directly:

https://chromium.googlesource.com/chromium/src.git/+/master/headless/

**Comment by Rob--W** [comment]
The library that you've linked is not a full version of Chromium, e.g. it does not support Chrome extensions.

If you really want to use `headless_shell`, then it's as simple as launching it in a child process.

**Comment by graingert** [comment]
@Rob--W how do I launch headless_shell?

**Comment by Rob--W** [comment]
@graingert What part of the documentation that you linked is unclear? After compiling it, it can just be ran, e.g. `path/to/src/out/Release/headless_shell`.

If you wonder how to start it in Node.js, see https://nodejs.org/api/child_process.html

**Comment by graingert** [comment]
@Rob--W ah I see, that makes sense, thanks.
