### ISSUE TITLE
Let's add some colors

### ISSUE THREAD

**Issue by mdamien** [CodeYellowBV/run-headless-chromium#7]
Would be nice to get the chrome logs dimmed, the console.error red and the other color stuff.

**Comment by Rob--W** [comment]
Pull requests are welcome. Suggestion: Check whether an environment variable exists and use the [`colors` package](https://www.npmjs.com/package/colors) to add colors.

**Comment by mdamien** [comment]
Ok, any advice to get the values of the color (e.g `color` in `console.log('%c test', color)) ? Looks like there's no way to get them (via a [quick look a the doc](https://www.chromium.org/for-testers/enable-logging) or the [logging.h](https://chromium.googlesource.com/chromium/src/+/master/base/logging.h))

I would say it's not worth the effort after looking into it.

**Comment by Rob--W** [comment]
Chrome only prints the first parameter to `console.log` (info, debug, error, warn, ... - https://crbug.com/365427), so you cannot use `%c`. If you want to add colored logs, edit the Node.js script to add custom colors.

The Node script parses the output of the Chromium executable, so it does know the difference between error/log/info, etc.

**Comment by mdamien** [comment]
Yes, closing the issue as a non-issue since it can be done by another script on top (like `lolcat`). Yeah for the unix philosophy !
